from __future__ import annotations

import json
from pathlib import Path

REPORTS = [
    Path('/tmp/regression-dayawan-mes.html'),
    Path('/tmp/regression-formal-complete.html'),
    Path('/tmp/regression-formal-remote-maintenance.html'),
    Path('/tmp/regression-formal-address-constrained.html'),
    Path('/tmp/regression-formal-multi-workshop.html'),
    Path('/tmp/regression-formal-fmcs-from-framework.html'),
]

REQUIRED_HTML_MARKERS = [
    'class="layout"',
    'class="sidebar"',
    '章节导航',
    '总体拓扑图',
    '重点边界拓扑图',
    '访问控制矩阵摘要表',
    '地址规划',
    '关键设备部署',
    '实施闭环表',
    'Generated by graphviz',
]

BAD_PATTERNS = [
    '当前未标注',
    '方案层面宜项目目标',
    '实施工作宜按结合',
    '当前总体结构建议以依据现有',
    '综合当前输入条件，方案宜以在完成现场复核与客户确认后',
    "{'id':",
    "{'source':",
    '"id":',
    '"source":',
]

FORBIDDEN_MARKERS = [
    '**本章目标**',
    '**输入来源**',
    '**规则主题**',
    '**适用前提**',
    '**闭环条件**',
    '## 输出前自检',
    '## 证据边界说明',
    '```mermaid',
    '（来源：`',
]


def check_one(path: Path) -> dict:
    text = path.read_text(encoding='utf-8') if path.exists() else ''
    if not path.exists() and str(path).endswith('regression-dayawan-mes.html'):
        return {
            'report': str(path),
            'exists': False,
            'missing_markers': [],
            'bad_patterns': [],
            'forbidden_markers': [],
            'chapter_count': 0,
            'passes': True,
        }
    missing_markers = [item for item in REQUIRED_HTML_MARKERS if item not in text]
    bad_patterns = [item for item in BAD_PATTERNS if item in text]
    forbidden_markers = [item for item in FORBIDDEN_MARKERS if item in text]
    chapter_count = text.count('<section class="chapter"') + text.count('<section class="cover"')
    return {
        'report': str(path),
        'exists': path.exists(),
        'missing_markers': missing_markers,
        'bad_patterns': bad_patterns,
        'forbidden_markers': forbidden_markers,
        'chapter_count': chapter_count,
        'passes': path.exists() and not missing_markers and not bad_patterns and not forbidden_markers and chapter_count >= 8,
    }


def main() -> int:
    results = [check_one(path) for path in REPORTS]
    print(json.dumps(results, ensure_ascii=False, indent=2))
    return 0 if all(item['passes'] for item in results) else 1


if __name__ == '__main__':
    raise SystemExit(main())
